// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2UHbPuVs8-jNKceA0u8AtqYYJQch--o',
    appId: '1:888609703277:web:06f72f3461c06c5a860664',
    messagingSenderId: '888609703277',
    projectId: 'sria-cashora',
    authDomain: 'sria-cashora.firebaseapp.com',
    storageBucket: 'sria-cashora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjqIQJCEfrKWumeCz8m4mltZqRIZkp8ck',
    appId: '1:888609703277:android:db4c6a924fc10abd860664',
    messagingSenderId: '888609703277',
    projectId: 'sria-cashora',
    storageBucket: 'sria-cashora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFb8_igp_Em6aoDyr8Ij1RgqTN6AZYp5E',
    appId: '1:888609703277:ios:c8fd33b9e7033220860664',
    messagingSenderId: '888609703277',
    projectId: 'sria-cashora',
    storageBucket: 'sria-cashora.firebasestorage.app',
    iosBundleId: 'com.cashora.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFb8_igp_Em6aoDyr8Ij1RgqTN6AZYp5E',
    appId: '1:888609703277:ios:c8fd33b9e7033220860664',
    messagingSenderId: '888609703277',
    projectId: 'sria-cashora',
    storageBucket: 'sria-cashora.firebasestorage.app',
    iosBundleId: 'com.cashora.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW2UHbPuVs8-jNKceA0u8AtqYYJQch--o',
    appId: '1:888609703277:web:edd19693cc5b2d84860664',
    messagingSenderId: '888609703277',
    projectId: 'sria-cashora',
    authDomain: 'sria-cashora.firebaseapp.com',
    storageBucket: 'sria-cashora.firebasestorage.app',
  );
}
